-- Car Maintenance Log Database Schema
-- For DigitalOcean MySQL Database
-- Run this script to initialize your database

-- Create database (uncomment if you need to create the database)
-- CREATE DATABASE IF NOT EXISTS car_maintenance_log CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shane_db;

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255),
  password VARCHAR(255),
  role ENUM('admin', 'user') DEFAULT 'user',
  googleId VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_google_id (googleId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create maintenance_logs table
CREATE TABLE IF NOT EXISTS maintenance_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  carMake VARCHAR(255) NOT NULL,
  carModel VARCHAR(255) NOT NULL,
  serviceType VARCHAR(255) NOT NULL,
  serviceDate DATE NOT NULL,
  mileage INT,
  cost DECIMAL(10, 2),
  notes TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_service_date (serviceDate),
  INDEX idx_car (carMake, carModel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert admin user (password: admin)
-- Note: The password hash will be generated by the application
-- This is a placeholder - the application will create the admin user automatically
-- But you can also insert it manually after hashing the password with bcrypt

-- To create admin user manually:
-- You'll need to hash 'admin' password using bcrypt (10 rounds)
-- Example hash (for password 'admin'): $2a$10$... (run through bcrypt.hash('admin', 10))
-- INSERT INTO users (email, name, password, role) 
-- VALUES ('admin@admin.com', 'Admin', '$2a$10$YOUR_BCRYPT_HASH_HERE', 'admin')
-- ON DUPLICATE KEY UPDATE email=email;

